### PR TITLE
Just a suggestion (doesn't actually work!)

### PR DESCRIPTION
**Pull request by Rob-H**

### CODE REVIEW

**Comment by ceilfors** [comment]
That's a good idea! 1 less required parameter as it's not a 'dependency' peer in the first place.

I presume 'end' event is only fired when all items are done processing and won't be fired when it is still recursing?

**Comment by Rob-H** [comment]
yeah, I was thinking only when it's finished recursing completely and all items have been dealt with. It could be useful, even if it's just logging that the process was finished or cleaning up resources or temporary data

**Comment by ceilfors** [comment]
Helpful.

The implementation looks like this now, as I'm going to have to return a function in the final chain. What do you think?

```
module.exports = dynamoDbBatch(
  'SCAN',
  { TableName: 'Music' }
)
.on('item', (item, event, context) => ...)
.on('end', console.log)
.handler()
```

**Comment by Rob-H** [comment]
I think that's pretty good, in some ways it's nice to be explicit with the handler call. However if you did want to be super *fluent* then functions are objects too, so I think you could add an `on` property to a function and return itself. e.g. 

    dynamoDbBatch = (args) => {
       const itemHandlers = []
       const endHandlers = []
       const batcchHandlers = []
       const handler = (event, context) => {
               .......
        }
        handler.on = (event, eventHandler) =>{
              //add event handler to appropriate array
              return handler 
        }
        return handler
    }

**Comment by ceilfors** [comment]
Thanks.

Don't think I understand what you mean by super fluent. How will the above implementation differ in term of usage?

**Comment by ceilfors** [comment]
I think I just understood what you meant! You were proposing on how I can eliminate the need of calling .handler(). That's quite creative. I guess it's down to:

```
module.exports.handler = dynamoDbBatchHandler(
  'SCAN',
  { TableName: 'Music' }
)
.on('item', (item, event, context) => ...)
```

or

```
module.exports.handler = dynamoDbBatch(
  'SCAN',
  { TableName: 'Music' }
)
.on('item', (item, event, context) => ...)
.handler()
```

Thinking out loud, I think I'll try to implement the first one as I'm not actually limited by the language's limitation. Most importantly, even though the second one is more explicit, the first one is a poka-yoke.

**Comment by ceilfors** [comment]
Thanks for the suggestion again, this is now done at bc6635633d290c22f15de0e17b5e094a8ab93cb8!

**Pull request closed without merging**
